name: Build all

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
    strategy:
      fail-fast: false
      matrix:
        include:
          - app-path: sitzverteilung-frontend

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@54b32c7d11363cad45838c9a3d8a8560b93f0e8c # v1.5.4
      - if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path))!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@54b32c7d11363cad45838c9a3d8a8560b93f0e8c # v1.5.4
        with:
          app-path: ${{ matrix.app-path }}