name: build push master sitzverteilung-app

on:
  push:
    branches:
      - master
    paths:
      - '../../sitzverteilung-app/**'
      - 'sitzverteilung-app_push-master.yml'

jobs:
  build-github-container-image:
    permissions:
      packages: write
    uses:
      ./.github/workflows/callable-create-github-container-image.yml
    with:
      service: 'sitzverteilung-app'