name: build push master sitzverteilung-service

on:
  push:
    branches:
      - master
    paths:
      - 'sitzverteilung-service/**'
      - '.github/workflows/sitzverteilung-service_push-master.yml'

jobs:
  build-github-container-image:
    permissions:
      packages: write
    uses:
      ./.github/workflows/callable-create-github-container-image.yml
    with:
      service: 'sitzverteilung-service'